fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    mysql:
      repo: "git://github.com/puppetlabs/puppetlabs-mysql.git"
    dirtree:
      repo: "https://github.com/AlexCline/dirtree"
    epel:
      repo: "http://github.com/stahnma/puppet-module-epel"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    apache:
      repo: "https://github.com/puppetlabs/puppetlabs-apache"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
  symlinks:
    ratticdb: "#{source_dir}"
