forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-stdlib', '4.17.0'
mod 'puppetlabs-mysql', '3.11.0'
mod 'AlexCline-dirtree', '0.2.1'
mod 'stahnma-epel', '1.2.2'
mod 'puppetlabs-apt', '2.2.2'
mod 'puppetlabs-apache', '1.8.1'
mod 'puppetlabs-concat', '2.2.1'


